dubbo:
  scan:
    base-packages: com.example.engine.service    # Dubbo 服务实现类的扫描基准包
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://127.0.0.1:8848

# 測試配置中心
test:
  user:
    name: gbz

# mybatis plus 配置
mybatis-plus:
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断" ,NOT_EMPTY:"字符串非空判断"
      #查看FieldStrategy类
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-field: flag    # 全局逻辑删除的实体字段名，实体可用@TableLogic
      logic-delete-value: 0
      logic-not-delete-value: 1
      #数据库类型
      db-type: mysql
    #关闭热加载
    refresh: false
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 关闭二级缓存
    cache-enabled: false
    # 打日志到控制台（可以使用它的兄弟类，打印到其它地方）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    druid:
      filters: 'stat,wall,slf4j'
      initial-size: 5
      max-active: 120
      max-pool-prepared-statement-per-connection-size: 80
      max-wait: 6000
      min-evictable-idle-time-millis: 600000
      min-idle: 5
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: select 1
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/user1
    username: root
